# Datasource
server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://database.cutq8zwu23mt.us-west-2.rds.amazonaws.com:3306/sample
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

# Flyway
  flyway:
    enabled: false

# Liquibase
  liquibase:
    enabled: false

# Cors configuration
application:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 3600
# Security configuration
  security:
    base64-secret: 'MTg0ZDY3MDMxNTUwN2YwNDU5OWM5YjNjOGQzODcwZDk2ZDk4ZTJlZTQzZTA4YjFjNjlhNGEyOWVlMGI4YjYxZjdiNTdhYzVkMWE1YmVjMmFjMTdmZTBmYmViZWRkNDI2OGJjY2NmZDhlNzllYzBmMTAzMTc4NzJjNjMxY2UxM2Y='
    token-validity-in-seconds: 86400
# Kafka
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group.id: sample
    auto.offset.reset: earliest
  producer:
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer


